/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    events: Event;
    registrations: Registration;
    announcements: Announcement;
    dailyReports: DailyReport;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    dailyReports: DailyReportsSelect<false> | DailyReportsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    teamPolicies: TeamPolicy;
  };
  globalsSelect: {
    teamPolicies: TeamPoliciesSelect<false> | TeamPoliciesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * 隊員常用稱呼。
   */
  displayName: string;
  /**
   * 報名活動使用的姓名。
   */
  realName?: string | null;
  role: 'admin' | 'cadre' | 'user';
  phone?: string | null;
  emergencyContact?: {
    name?: string | null;
    phone?: string | null;
    relationship?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  tripType: 'hundredPeaks' | 'regular';
  status: 'planning' | 'open' | 'full' | 'ended' | 'canceled';
  startDate: string;
  endDate: string;
  price: number;
  capacity?: number | null;
  leaders?: (string | User)[] | null;
  /**
   * 查詢個人登山履歷時會優先使用這裡的名稱。
   */
  mountains?:
    | {
        name: string;
        elevationMeters?: number | null;
        isHundredPeak?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 給活動列表與摘要使用，建議 1-3 句。
   */
  summary?: string | null;
  itinerary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meetingPoint?: string | null;
  registrationNote?: string | null;
  coverImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: string;
  displayTitle?: string | null;
  mainContact: string | User;
  event: string | Event;
  status: 'pendingDocuments' | 'pendingPayment' | 'completed' | 'canceled';
  attendance: 'notSet' | 'absent' | 'attended' | 'retreated';
  participants?:
    | {
        linkedUser?: (string | null) | User;
        name: string;
        idNumber?: string | null;
        birthDate?: string | null;
        phone?: string | null;
        attendance?: ('notSet' | 'absent' | 'attended' | 'retreated') | null;
        id?: string | null;
      }[]
    | null;
  agreedToTerms: boolean;
  payment?: {
    amount?: number | null;
    paidAt?: string | null;
    note?: string | null;
  };
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title: string;
  type: 'general' | 'eventChange' | 'lostAndFound';
  status: 'draft' | 'published' | 'archived';
  publishAt?: string | null;
  pinned?: boolean | null;
  /**
   * 給公告摘要快速列點使用；未填時可退回讀公告內容。
   */
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedEvent?: (string | null) | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyReports".
 */
export interface DailyReport {
  id: string;
  /**
   * 格式：YYYY-MM-DD，以台灣時間為準。
   */
  reportDate: string;
  status: 'draft' | 'generated' | 'sent' | 'failed';
  sentAt?: string | null;
  sentTarget?: string | null;
  sentBy?: string | null;
  sentItemCount?: number | null;
  sentItems?:
    | {
        kind?: string | null;
        label?: string | null;
        mediaId?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  part1?: {
    generatedAt?: string | null;
    newsSourceUrl?: string | null;
    newsItems?:
      | {
          title: string;
          url: string;
          source?: string | null;
          excerpt?: string | null;
          id?: string | null;
        }[]
      | null;
    cryptobubblesScreenshot?: (string | null) | Media;
    coin360Screenshot?: (string | null) | Media;
    notes?: string | null;
  };
  part2?: {
    generatedAt?: string | null;
    cteeSourceUrl?: string | null;
    economicDailySourceUrl?: string | null;
    cteeNewspaperScreenshot?: (string | null) | Media;
    cteeNewspaperPage2Screenshot?: (string | null) | Media;
    cteeNewspaperPage3Screenshot?: (string | null) | Media;
    economicDailyScreenshot?: (string | null) | Media;
    economicDailyPage2Screenshot?: (string | null) | Media;
    economicDailyPage3Screenshot?: (string | null) | Media;
    notes?: string | null;
  };
  part3?: {
    generatedAt?: string | null;
    chinaSourceUrl?: string | null;
    worldSourceUrl?: string | null;
    usStockHeatmapSourceUrl?: string | null;
    globalStockCloseSourceUrl?: string | null;
    chinaDigestImage?: (string | null) | Media;
    worldDigestImage?: (string | null) | Media;
    usStockHeatmapImage?: (string | null) | Media;
    globalStockCloseImage?: (string | null) | Media;
    chinaItems?:
      | {
          title: string;
          summary?: string | null;
          url: string;
          id?: string | null;
        }[]
      | null;
    worldItems?:
      | {
          title: string;
          summary?: string | null;
          url: string;
          id?: string | null;
        }[]
      | null;
    notes?: string | null;
  };
  errorLogs?:
    | {
        scope?: string | null;
        message?: string | null;
        occurredAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: string | Registration;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'dailyReports';
        value: string | DailyReport;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  realName?: T;
  role?: T;
  phone?: T;
  emergencyContact?:
    | T
    | {
        name?: T;
        phone?: T;
        relationship?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  tripType?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  price?: T;
  capacity?: T;
  leaders?: T;
  mountains?:
    | T
    | {
        name?: T;
        elevationMeters?: T;
        isHundredPeak?: T;
        id?: T;
      };
  summary?: T;
  itinerary?: T;
  meetingPoint?: T;
  registrationNote?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  displayTitle?: T;
  mainContact?: T;
  event?: T;
  status?: T;
  attendance?: T;
  participants?:
    | T
    | {
        linkedUser?: T;
        name?: T;
        idNumber?: T;
        birthDate?: T;
        phone?: T;
        attendance?: T;
        id?: T;
      };
  agreedToTerms?: T;
  payment?:
    | T
    | {
        amount?: T;
        paidAt?: T;
        note?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  status?: T;
  publishAt?: T;
  pinned?: T;
  summary?: T;
  content?: T;
  relatedEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dailyReports_select".
 */
export interface DailyReportsSelect<T extends boolean = true> {
  reportDate?: T;
  status?: T;
  sentAt?: T;
  sentTarget?: T;
  sentBy?: T;
  sentItemCount?: T;
  sentItems?:
    | T
    | {
        kind?: T;
        label?: T;
        mediaId?: T;
        url?: T;
        id?: T;
      };
  part1?:
    | T
    | {
        generatedAt?: T;
        newsSourceUrl?: T;
        newsItems?:
          | T
          | {
              title?: T;
              url?: T;
              source?: T;
              excerpt?: T;
              id?: T;
            };
        cryptobubblesScreenshot?: T;
        coin360Screenshot?: T;
        notes?: T;
      };
  part2?:
    | T
    | {
        generatedAt?: T;
        cteeSourceUrl?: T;
        economicDailySourceUrl?: T;
        cteeNewspaperScreenshot?: T;
        cteeNewspaperPage2Screenshot?: T;
        cteeNewspaperPage3Screenshot?: T;
        economicDailyScreenshot?: T;
        economicDailyPage2Screenshot?: T;
        economicDailyPage3Screenshot?: T;
        notes?: T;
      };
  part3?:
    | T
    | {
        generatedAt?: T;
        chinaSourceUrl?: T;
        worldSourceUrl?: T;
        usStockHeatmapSourceUrl?: T;
        globalStockCloseSourceUrl?: T;
        chinaDigestImage?: T;
        worldDigestImage?: T;
        usStockHeatmapImage?: T;
        globalStockCloseImage?: T;
        chinaItems?:
          | T
          | {
              title?: T;
              summary?: T;
              url?: T;
              id?: T;
            };
        worldItems?:
          | T
          | {
              title?: T;
              summary?: T;
              url?: T;
              id?: T;
            };
        notes?: T;
      };
  errorLogs?:
    | T
    | {
        scope?: T;
        message?: T;
        occurredAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamPolicies".
 */
export interface TeamPolicy {
  id: string;
  policyContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  refundPolicy?:
    | {
        tripType: 'hundredPeaks' | 'regular';
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 建議整理成 AI 可以直接引用的簡短版本。
   */
  aiSummary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teamPolicies_select".
 */
export interface TeamPoliciesSelect<T extends boolean = true> {
  policyContent?: T;
  refundPolicy?:
    | T
    | {
        tripType?: T;
        description?: T;
        id?: T;
      };
  aiSummary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}